twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        siteName: '%app_name%'
    form_themes:
        - 'bootstrap_5_layout.html.twig'

when@test:
    twig:
        strict_variables: true
